// lib/wordList.js

export const WORD_CATEGORIES = {
  everyday: {
    label: "🏠 Everyday Talk",
    desc: "Common daily life words",
    words: {
      easy: [
        "grateful","patient","reliable","sincere","flexible","cheerful","polite",
        "cautious","curious","generous","honest","humble","kind","loyal","modest",
        "calm","caring","clear","content","creative","dedicated","earnest","fair",
        "focused","frank","giving","happy","healthy","helpful","hopeful","joyful",
        "mindful","natural","noble","peaceful","polite","proud","quiet","ready",
        "safe","smart","strong","sweet","tidy","tired","tough","true","warm","wise",
        "young","brave","clean","clever","eager","early","easy","fast","firm","free",
        "full","glad","good","kind","late","lean","lively","loud","neat","nice",
        "open","plain","pure","real","rich","rough","round","sharp","short","shy",
        "slow","soft","still","thin","wild","worn","able","active","actual","alert",
        "alive","angry","awake","aware","basic","bold","busy","cheap","close","cold",
        "cool","cruel","cute","dark","dead","deep","dirty","dull","dumb","fair",
        "fake","far","fit","flat","fresh","funny","giant","great","gross","grown",
        "hard","huge","idle","jolly","just","late","lazy","left","less","light",
        "like","little","lost","loud","low","lucky","mad","main","mean","mild",
        "neat","new","next","nice","odd","okay","old","only","other","outer",
        "own","pale","past","pink","poor","quiet","rare","raw","red","ripe",
        "rude","sad","same","sick","slim","slow","small","sour","spare","sweet",
        "tall","thick","tight","tiny","true","ugly","used","vague","vast","warm",
        "weak","weird","well","wet","wide","wild","wise","witty","wrong","young",
      ],
      medium: [
        "adequate","abundant","balanced","capable","composed","confident","decent",
        "diligent","efficient","energetic","faithful","gentle","gracious","handy",
        "independent","intuitive","jovial","keen","mature","nurturing","optimistic",
        "persistent","practical","punctual","rational","responsible","sensible",
        "steady","tender","thoughtful","tolerant","unique","vibrant","zealous",
        "affable","amiable","attentive","benevolent","candid","coherent","cordial",
        "courteous","dependable","empathetic","enduring","ethical","frugal","genuine",
        "grounded","hardworking","impartial","judicious","levelheaded","methodical",
        "observant","organized","perceptive","principled","proactive","prudent",
        "reflective","resilient","resourceful","self-aware","sociable","strategic",
        "systematic","tactful","versatile","wholesome","accommodating","adaptable",
        "analytical","appreciative","articulate","assertive","broad-minded","careful",
        "charitable","communicative","community-minded","compassionate","conscientious",
        "considerate","constructive","cooperative","courageous","decisive","deliberate",
        "determined","diplomatic","discerning","driven","earnest","effective","empowering",
        "encouraging","equitable","experienced","forthright","forward-thinking","friendly",
        "fulfilling","goal-oriented","grounded","growth-minded","helpful","honest",
        "imaginative","inclusive","industrious","informed","insightful","inspiring",
        "integrous","intentional","inventive","involved","kind-hearted","knowledgeable",
        "leaders","learning","mindful","moral","motivated","open-minded","optimistic",
        "passionate","patient","positive","prepared","proactive","productive",
        "professional","progressive","purposeful","qualified","receptive","reliable",
        "respectful","responsible","self-disciplined","service-oriented","sincere",
        "skilled","solution-focused","supportive","sustainable","team-oriented",
        "thorough","trustworthy","understanding","upstanding","values-driven","vigilant",
      ],
      advanced: [
        "magnanimous","equanimous","perspicacious","judicious","circumspect",
        "tenacious","sagacious","scrupulous","conscientious","indefatigable",
        "philanthropic","altruistic","benevolent","meticulous","assiduous",
        "contemplative","discerning","eloquent","fastidious","forthright",
        "inquisitive","introspective","magnanimous","methodical","persevering",
        "principled","prudential","reflective","resolute","steadfast","temperate",
        "unassuming","veracious","vigilant","virtuous","wholehearted","abstemious",
        "acumen","amenable","astute","attentive","austere","authentic","benign",
        "cerebral","charitable","cogent","coherent","composure","conciliatory",
        "conscientious","contemplative","conviction","credible","deliberative",
        "dependable","dignified","diplomatic","discerning","discreet","dutiful",
        "earnest","ebullient","edifying","effectual","egalitarian","empathic",
        "enlightened","equitable","estimable","ethical","exemplary","expedient",
        "forthright","frugal","genuine","gracious","honorable","humane","impartial",
        "impeccable","industrious","ingenuous","insightful","integrous","judicious",
        "magnanimous","meritorious","methodical","moderate","moral","noble",
        "nurturing","objective","open-minded","patient","peaceable","perceptive",
        "perseverant","philanthropic","pious","placid","pragmatic","principled",
        "prodigious","profound","progressive","prudent","pure-hearted","rational",
        "reasonable","rectitudinous","reliable","resolute","resourceful","righteous",
        "sagacious","scrupulous","self-disciplined","serene","sincere","steadfast",
        "stoic","sympathetic","tenacious","thoughtful","tolerant","trustworthy",
        "unbiased","understanding","upright","valiant","veracious","virtuous",
        "wholesome","wise","zealous","abiding","abnegating","abstemious","acclaimed",
      ],
    }
  },

  casual: {
    label: "😎 Casual Talk",
    desc: "Relaxed informal conversations",
    words: {
      easy: [
        "fun","cool","nice","good","great","chill","wild","bold","free","bright",
        "calm","sharp","smart","quick","light","loud","lively","jolly","happy",
        "funny","witty","brave","kind","warm","easy","clean","fresh","open","clear",
        "safe","real","pure","true","best","fine","fair","full","glad","fast",
        "loud","slow","soft","hard","long","high","low","big","tiny","huge",
        "sweet","sour","dry","wet","hot","cold","new","old","young","raw",
        "rare","ripe","rich","poor","lazy","busy","noisy","quiet","messy","neat",
        "rough","smooth","round","flat","short","tall","thin","fat","wide","narrow",
        "light","dark","bright","dim","loud","silent","fast","slow","strong","weak",
        "happy","sad","angry","scared","excited","bored","tired","awake","hungry","full",
        "thirsty","sick","well","lost","found","ready","busy","free","late","early",
        "near","far","left","right","up","down","in","out","on","off","open","shut",
        "hot","warm","cool","cold","wet","dry","clean","dirty","new","old","big","small",
        "long","short","high","low","fast","slow","hard","soft","loud","quiet","heavy","light",
      ],
      medium: [
        "spontaneous","quirky","whimsical","banter","amusing","breezy","bubbly",
        "carefree","charming","clever","colorful","comical","daring","dazzling",
        "eccentric","entertaining","enthusiastic","exciting","feisty","flamboyant",
        "funky","goofy","gutsy","hilarious","imaginative","impulsive","irreverent",
        "lighthearted","mischievous","offbeat","outgoing","outspoken","playful",
        "sassy","savvy","snappy","spunky","suave","trendy","unconventional","upbeat",
        "vivacious","wacky","zany","adventurous","animated","brash","casual","cheeky",
        "dynamic","easy-going","free-spirited","gregarious","hyper","impromptu",
        "informal","laidback","nonchalant","peppy","perky","quirky","rambunctious",
        "rowdy","spirited","spontaneous","sprightly","unfiltered","unscripted",
        "unpretentious","unreserved","unrestrained","vivid","whimsical","witty",
        "youthful","zesty","approachable","boisterous","breezy","candid","carefree",
        "chatty","chipper","convivial","easygoing","exuberant","flippant","folksy",
        "friendly","fun-loving","genial","good-humored","happy-go-lucky","jolly",
        "jovial","laid-back","merry","personable","playful","relaxed","sociable",
        "sunny","talkative","unassuming","uninhibited","uplifting","warm","welcoming",
        "affable","airy","amicable","blithe","bouncy","capricious","casual","cheerful",
        "chilled","colloquial","comfortable","companionable","cool","cordial","droll",
      ],
      advanced: [
        "ebullient","effervescent","exuberant","vivacious","scintillating",
        "convivial","gregarious","loquacious","garrulous","facetious","waggish",
        "jocular","whimsical","capricious","mercurial","flippant","irreverent",
        "iconoclastic","unconventional","unorthodox","idiosyncratic","quirky",
        "nonconformist","bohemian","maverick","spontaneous","improvisational",
        "extemporaneous","unpretentious","unaffected","guileless","artless",
        "ingenuous","candid","forthright","uninhibited","unrestrained","libertine",
        "hedonistic","epicurean","sybaritic","indulgent","carefree","insouciant",
        "nonchalant","blithe","sanguine","buoyant","resilient","indomitable",
        "irrepressible","zestful","enthusiastic","fervent","ardent","passionate",
        "vivid","colorful","flamboyant","ostentatious","theatrical","dramatic",
        "histrionic","melodramatic","hyperbolic","effusive","gushing","rhapsodic",
        "ecstatic","euphoric","elated","exhilarated","exuberant","jubilant",
        "rapturous","transported","enraptured","enthralled","captivated","enchanted",
        "spellbound","mesmerized","fascinated","intrigued","curious","inquisitive",
        "exploratory","adventurous","intrepid","audacious","daring","bold","fearless",
        "undaunted","unflinching","resolute","determined","tenacious","persistent",
        "dogged","relentless","unstoppable","irresistible","compelling","magnetic",
        "charismatic","captivating","enchanting","alluring","fascinating","intriguing",
        "mysterious","enigmatic","elusive","ineffable","indescribable","inexplicable",
      ],
    }
  },

  office: {
    label: "💼 Office Talk",
    desc: "Professional workplace vocabulary",
    words: {
      easy: [
        "plan","goal","task","team","work","meet","lead","help","build","grow",
        "share","talk","hire","fire","boss","staff","sale","cost","gain","loss",
        "deal","idea","note","file","send","call","chat","form","list","track",
        "time","rate","step","rule","role","rank","case","base","line","name",
        "data","fund","word","page","user","tool","code","test","ship","fix",
        "add","cut","get","set","run","pay","buy","sell","earn","owe","own","use",
        "make","take","give","keep","hold","bring","show","find","tell","need",
        "want","know","think","feel","seem","look","turn","come","go","see",
        "say","ask","answer","write","read","print","save","open","close","start",
        "stop","push","pull","move","copy","paste","delete","create","edit","view",
        "sort","filter","search","select","check","mark","sign","seal","send","receive",
        "approve","reject","review","submit","confirm","cancel","update","upgrade","install",
        "download","upload","login","logout","register","verify","notify","remind","alert",
      ],
      medium: [
        "collaborate","delegate","facilitate","implement","leverage","optimize",
        "prioritize","streamline","strategize","synthesize","accelerate","achieve",
        "allocate","analyze","articulate","assess","benchmark","brainstorm",
        "champion","clarify","communicate","coordinate","cultivate","deadline",
        "debrief","decisive","deploy","develop","differentiate","document",
        "drive","empower","evaluate","execute","expedite","forecast","formulate",
        "govern","guide","identify","initiative","innovate","integrate","iterate",
        "launch","manage","measure","mentor","milestone","mobilize","monitor",
        "motivate","negotiate","network","organize","oversee","perform","present",
        "produce","project","promote","propose","recommend","report","resolve",
        "review","revise","scale","schedule","scope","structure","summarize",
        "support","sustain","target","transform","update","validate","visualize",
        "alignment","bandwidth","capacity","deliverable","ecosystem","framework",
        "headcount","holistic","incentive","metric","paradigm","pipeline","roadmap",
        "accountability","adaptability","agility","autonomy","clarity","cohesion",
        "commitment","competency","compliance","consistency","continuity","creativity",
        "cross-functional","customer-centric","data-driven","decision-making",
        "efficiency","engagement","excellence","execution","feedback","flexibility",
        "focus","governance","growth","impact","inclusion","innovation","integrity",
        "leadership","learning","ownership","performance","planning","process",
        "productivity","professionalism","quality","reliability","scalability",
        "stakeholder","sustainability","synergy","talent","teamwork","transparency",
        "trust","value","velocity","vision","workflow","workload","workplace",
      ],
      advanced: [
        "perspicacious","circumspect","sagacious","judicious","astute","acumen",
        "strategic","visionary","transformative","disruptive","innovative","agile",
        "scalable","sustainable","synergistic","holistic","systematic","methodical",
        "analytical","empirical","evidence-based","data-driven","outcome-oriented",
        "results-driven","performance-oriented","accountability","transparency",
        "governance","compliance","regulatory","fiduciary","stakeholder","shareholder",
        "equity","valuation","capitalization","monetization","optimization","efficiency",
        "productivity","profitability","sustainability","scalability","viability",
        "feasibility","ROI","KPI","OKR","SWOT","PESTLE","benchmarking","baselining",
        "forecasting","modeling","simulation","prototyping","iteration","pivot",
        "disruption","transformation","innovation","differentiation","positioning",
        "branding","marketing","segmentation","targeting","acquisition","retention",
        "engagement","conversion","funnel","pipeline","velocity","throughput",
        "bottleneck","constraint","dependency","risk","mitigation","contingency",
        "resilience","redundancy","continuity","recovery","remediation","escalation",
        "arbitration","mediation","negotiation","collaboration","coordination",
        "integration","alignment","cohesion","synergy","leverage","optimization",
        "streamlining","automation","digitization","transformation","modernization",
        "consolidation","restructuring","reorganization","reengineering","revitalization",
        "turnaround","growth","expansion","diversification","verticalization","globalization",
        "localization","customization","personalization","standardization","normalization",
        "harmonization","rationalization","simplification","clarification","specification",
      ],
    }
  },

  friends: {
    label: "👫 Friend Talk",
    desc: "Words for talking with close friends",
    words: {
      easy: [
        "kind","warm","true","real","good","nice","safe","open","free","fun",
        "calm","soft","glad","dear","close","brave","fair","pure","fond","mild",
        "sweet","loyal","happy","honest","caring","giving","loving","joyful",
        "gentle","sincere","helpful","patient","faithful","cheerful","friendly",
        "thankful","hopeful","peaceful","pleasant","positive","trusting","forgiving",
        "sharing","willing","easy","ready","steady","reliable","comfortable","familiar",
        "likable","relatable","approachable","welcoming","accepting","understanding",
        "supportive","encouraging","reassuring","motivating","uplifting","inspiring",
        "amusing","entertaining","interesting","engaging","attentive","present","focused",
        "listening","hearing","seeing","knowing","feeling","caring","helping","sharing",
        "giving","loving","supporting","encouraging","uplifting","motivating","inspiring",
        "comforting","reassuring","calming","soothing","healing","nurturing","growing",
        "learning","teaching","sharing","bonding","connecting","relating","empathizing",
        "understanding","accepting","forgiving","supporting","trusting","believing",
        "hoping","caring","loving","giving","sharing","helping","healing","growing",
        "bonding","connecting","relating","understanding","accepting","supporting",
        "trusting","believing","caring","loving","helping","sharing","giving","uplifting",
      ],
      medium: [
        "candid","empathetic","nostalgic","vulnerable","genuine","supportive",
        "affectionate","appreciative","attentive","bonding","cherish","comfortable",
        "compassionate","confide","connected","devoted","emotional","encouraging",
        "endearing","faithful","fond","forgiving","heartfelt","intimate","meaningful",
        "reassuring","relatable","reminisce","tender","transparent","trustworthy",
        "wholehearted","accepting","amicable","camaraderie","considerate","dependable",
        "empathize","fellowship","goodwill","gracious","harmonious","kindhearted",
        "loving","mellow","mutual","neighborly","nurturing","obliging","pleasant",
        "pleasing","receptive","respectful","selfless","sociable","sympathetic",
        "tactful","unselfish","warmhearted","welcoming","well-meaning","willing",
        "accommodating","adaptable","amiable","benevolent","charitable","cheerful",
        "comfortable","comforting","committed","communicative","compassionate",
        "cooperative","devoted","easygoing","empathetic","encouraging","faithful",
        "flexible","forgiving","friendly","fulfilling","generous","genuine","gracious",
        "grateful","grounded","harmonious","helpful","honest","humble","inclusive",
        "inspiring","involved","joyful","kind","lighthearted","loyal","mindful",
        "open","open-minded","patient","peaceful","positive","present","principled",
        "proactive","real","reliable","resilient","respectful","safe","secure",
        "self-aware","sensitive","sincere","thoughtful","trusting","understanding",
        "uplifting","valued","vibrant","warm","wholesome","willing","worthy","zealous",
      ],
      advanced: [
        "magnanimous","empathetic","altruistic","benevolent","compassionate",
        "equanimous","philanthropic","convivial","gregarious","loquacious","effusive",
        "sentimental","nostalgic","melancholic","wistful","bittersweet","poignant",
        "heartfelt","sincere","genuine","authentic","vulnerable","transparent","candid",
        "forthright","open","trusting","trustworthy","dependable","reliable","steadfast",
        "loyal","devoted","committed","dedicated","faithful","constant","unwavering",
        "abiding","enduring","lasting","permanent","eternal","timeless","immortal",
        "undying","everlasting","perpetual","infinite","boundless","limitless","endless",
        "unconditional","absolute","complete","total","whole","full","perfect","ideal",
        "pure","true","real","genuine","authentic","sincere","honest","candid","frank",
        "open","transparent","vulnerable","intimate","close","deep","profound","meaningful",
        "significant","important","valuable","precious","treasured","cherished","beloved",
        "adored","revered","esteemed","respected","admired","appreciated","recognized",
        "acknowledged","validated","understood","accepted","embraced","welcomed","included",
        "supported","encouraged","uplifted","empowered","inspired","motivated","energized",
        "nourished","nurtured","cared","loved","protected","safe","secure","comforted",
        "reassured","calmed","soothed","healed","restored","renewed","refreshed","revived",
        "rejuvenated","reinvigorated","reenergized","reborn","transformed","transcended",
      ],
    }
  },

  group: {
    label: "🎤 Group Talk",
    desc: "Speaking in meetings or groups",
    words: {
      easy: [
        "speak","talk","tell","say","ask","share","give","lead","help","show",
        "open","start","stop","next","last","first","main","key","big","clear",
        "brief","short","long","sure","true","right","good","great","best","fair",
        "agree","think","feel","know","want","need","mean","call","vote","pick",
        "choose","decide","suggest","answer","explain","describe","present","report",
        "list","note","point","flag","raise","lower","pause","wait","listen","watch",
        "read","write","draw","show","see","hear","feel","touch","move","stay",
        "sit","stand","join","leave","enter","exit","begin","end","close","open",
        "add","remove","include","exclude","accept","reject","approve","deny",
        "confirm","cancel","check","mark","record","track","follow","lead","guide",
        "direct","manage","control","organize","plan","prepare","arrange","coordinate",
        "support","assist","help","serve","contribute","participate","engage","involve",
        "collaborate","cooperate","work","act","do","make","build","create","develop",
        "grow","improve","change","update","fix","solve","resolve","handle","address",
      ],
      medium: [
        "articulate","assertive","concise","compelling","persuasive","eloquent",
        "authoritative","charismatic","coherent","confident","constructive",
        "contributive","credible","deliberate","diplomatic","direct","effective",
        "engaging","expressive","fluent","forceful","forthright","impactful",
        "inclusive","influential","informative","insightful","logical","measured",
        "mediate","moderate","motivating","objective","opinionated","organized",
        "outspoken","precise","proactive","prominent","purposeful","relevant",
        "respectful","rhetorical","structured","substantive","succinct","tactical",
        "transparent","unambiguous","vocal","well-spoken","accessible","balanced",
        "collaborative","committed","composed","decisive","definitive","dynamic",
        "empowering","enthusiastic","evidence-based","focused","genuine","grounded",
        "honest","informed","intentional","methodical","mindful","neutral","nuanced",
        "open-minded","participative","poised","polished","prepared","professional",
        "qualified","rational","reasonable","receptive","reliable","responsive",
        "self-aware","service-oriented","solution-focused","strategic","systematic",
        "team-oriented","thorough","thoughtful","trustworthy","understanding",
        "upstanding","values-driven","vigilant","visionary","well-informed","wise",
        "accommodating","adaptable","analytical","appreciative","broad-minded",
        "careful","charitable","communicative","compassionate","conscientious",
        "cooperative","courageous","discerning","driven","earnest","equitable",
        "experienced","forward-thinking","fulfilling","goal-oriented","growth-minded",
        "imaginative","industrious","inspiring","integrous","inventive","involved",
      ],
      advanced: [
        "perspicacious","circumspect","judicious","sagacious","astute","discerning",
        "eloquent","articulate","persuasive","compelling","authoritative","credible",
        "impactful","influential","charismatic","magnetic","captivating","inspiring",
        "motivating","empowering","transformative","visionary","strategic","tactical",
        "diplomatic","conciliatory","mediating","arbitrating","negotiating","facilitating",
        "synthesizing","integrating","harmonizing","aligning","coordinating","orchestrating",
        "moderating","adjudicating","deliberating","contemplating","reflecting","analyzing",
        "evaluating","assessing","critiquing","examining","investigating","exploring",
        "hypothesizing","theorizing","conceptualizing","frameworks","paradigms","models",
        "methodologies","approaches","strategies","tactics","techniques","mechanisms",
        "processes","systems","structures","architectures","designs","blueprints",
        "roadmaps","trajectories","pathways","directions","orientations","perspectives",
        "viewpoints","standpoints","positions","stances","attitudes","dispositions",
        "orientations","inclinations","tendencies","proclivities","propensities","biases",
        "assumptions","presuppositions","premises","axioms","postulates","hypotheses",
        "conjectures","speculations","theories","frameworks","models","paradigms",
        "worldviews","ideologies","philosophies","principles","values","ethics","norms",
        "standards","criteria","benchmarks","indicators","metrics","measures","outcomes",
        "results","impacts","effects","consequences","implications","ramifications",
        "repercussions","reverberations","ripples","cascades","feedback","loops",
        "cycles","patterns","trends","trajectories","directions","movements","shifts",
      ],
    }
  },
};

export const ALL_CATEGORIES = Object.keys(WORD_CATEGORIES);

export function getRandomWord(category, difficulty, seenWords = []) {
  const cat = WORD_CATEGORIES[category] || WORD_CATEGORIES.everyday;
  const words = cat.words[difficulty] || cat.words.medium;
  const unseen = words.filter(w => !seenWords.includes(w.toLowerCase()));
  const pool = unseen.length > 0 ? unseen : words;
  return pool[Math.floor(Math.random() * pool.length)];
}